version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: asistencia_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: asistencia_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - asistencia_postgres_data:/var/lib/postgresql/data

volumes:
  asistencia_postgres_data:
