version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: asistencia_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: asistencia_geofecing
      MYSQL_USER: jairo
      MYSQL_PASSWORD: jairo123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
